name: run-length-encoding
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: RunLength
  source-dirs: src
  dependencies:
  - split
  - regex-compat
tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - run-length-encoding
      - hspec
