name: acronym
version: 1.2.0.4

dependencies:
  - base

library:
  exposed-modules: Acronym
  source-dirs: src
  dependencies:
   - split
   - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
