name: isogram
version: 1.3.0.3

dependencies:
  - base

library:
  exposed-modules: Isogram
  source-dirs: src
  dependencies:
    - containers       # List here the packages you

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isogram
      - hspec
